name = "folder"
compatibility_date = "2025-03-10"
main = "./dist/server/index.mjs"
compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true

# Bindings for Cloudflare KV (metadata)
[[kv_namespaces]]
binding = "KV"
id = "<uuid>"

# Bindings for Cloudflare R2
[[r2_buckets]]
binding = "BLOB"
bucket_name = ""

[assets]
binding = "ASSETS"
directory = "./dist/public/"

[vars]
NUXT_SESSION_PASSWORD=""
NUXT_OAUTH_GITHUB_CLIENT_ID=""
NUXT_OAUTH_GITHUB_CLIENT_SECRET=""
NUXT_OAUTH_GOOGLE_CLIENT_ID=""
NUXT_OAUTH_GOOGLE_CLIENT_SECRET=""
